var tgTitle = "DIGITAL PATHWAYS - 4";

var treeStructure = ["class", "chapter", "type"];
var imagePath = "img/q_img/";

var questions = [
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(a) What did people do before eating at the community feast?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(b) What are people using as plates to eat their meal?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(c) How do people share and eat the meal together?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "(d) Where did they put the banana leaves after everyone finished eating?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Name the following:",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(a) The festival when people plant trees",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(b) The big tree under which elders gather",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(c) The outdoor game the children play",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(d) The leaves used as plates at the feast",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "(e) The villager who repaired the street light before the festival",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Write True or False for the following statements.",
      option: [
        "A large banyan tree stands at the corner of the playground where children gather.",
        "Mallika’s grandmother visits the park every morning.",
        "Villagers repaired benches and street lights together after Van Mahotsav.",
        "After the feast, banana leaves were buried and turned into plant food.",
        "People and places are part of our community.",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "If there were no park, school, bus stop, shop or hospital in your neighbourhood, how would your life change?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "What will Noor bring from her nursery, and where will she plant the saplings?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "How do people in your community help each other? Give one example.",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "How are the following people or places in our neighbourhood helpful to us?",
      option: ["Police", "Sweeper", "Doctor's clinic", "Shops"],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "What event took place just before the feast?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Who ran towards the cooking area?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "What kinds of food did the villagers bring?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Who brought the vegetables and cereals?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Why was the meal a special occasion?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "In your opinion, who else could help plan the festival? Write their names based on your understanding of the chapter.",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Van Mahotsav is celebrated every year from",
      option: [
        "(a) 1 to 7 July </br> (i) 1 to 7 July </br> (ii) 1 to 7 June </br> (iii) 1 to 7 May </br> (iv) 1 to 7 August",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "What did Mallika use for announcements?",
      option: [
        "(i) Microphone </br> (ii) Drum </br> (iii) Handbell </br> (iv) Banner",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "What did Sameer bring to fix the benches?",
      option: [
        "(i) Wood and nails </br> (ii) Paint and brushes </br> (iii) Stones and cement </br> (iv) Clay and bricks",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "What did Babita volunteer to repair?",
      option: [
        "(i) Benches </br> (ii) Street light </br> (iii) Bridge </br> (iv) Playground equipment",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Both A and R are true, and R correctly explains A.",
      option: [
        "(a) Both A and R are true, and R correctly explains A. </br> (b) Both A and R are true, but R does not explain A. </br> (c) A is true, but R is false. </br> (d) A is false, but R is true.",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "When and where is Uruka celebrated?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Uruka falls on the eve of which festival?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "What is the name of the small hut built by families?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "What foods do families cook for the festive feast?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "Describe the incident that occurred in Kanker, Chhattisgarh, as mentioned in the chapter (page 9).",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Solve the riddle and write the name.",
      option: [
        "I stand tall with wide roots. Elders rest under me.",
        "I hold food at the feast, then turn into plant food.",
        "A small hut made of bamboo and hay for Uruka.",
        "I join places so cars and bikes can travel.",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Match the following columns.",
      option: [
        "(a) Shopkeeper   (i) Connects areas for travel",
        "(b) School   (ii) Treats the sick",
        "(c) Police   (iii) Keep people safe",
        "(d) Health Centre   (iv) Helps students learn new things",
        "(e) Road   (v) Sells goods like food and clothes",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "1. Living Together",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Write the name of the people who said these:",
      option: [
        "On this Van Mahotsav, we will clean the park and plant trees around the park.",
        "My grandmother comes here with her friends every day for a morning walk.",
        "Yes, let us invite our family members too for this celebration.",
        "The park where we plan to hold the Van Mahotsav needs repairs.",
        "I will repair the street light next to the park.",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["bus"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "What did Navya point to when the bus passed the corner?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["letter"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "What did Dada ji say you could write and post in the red postbox?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["postman"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Who takes the letters from the postbox to the post office?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["sort"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "What does the post office do with letters before sending them to different places?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["health"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Fill in the blanks with correct words.",
      option: ["Hospitals offer ..................... services."],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["left"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Fill in the blanks with correct words.",
      option: ["On most maps, West is shown on the ....................."],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["fast"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Fill in the blanks with correct words.",
      option: ["Metro trains across cities run very ....................."],
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["elevated", "Teller Machine", "time"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Fill in the blanks with correct words.",
      option: [
        "(d) Long elevated ....................... help vehicles move above busy roads.",
        "(e) The term ATM stands for Automated ....................... Machine.",
        "(f) Handwritten letters sent through post office often took ....................... to get timely replies.",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "What is the machine called and what does it do?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "How did people get or send money before ATMs?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "How do mobile phones help with money transfers?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Why did Dada ji say that banks are important?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Do you save money? If yes, then write what you do to save it.",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "Ask your parents or elders in the family to know the situations in which they use online money transfers. List any four examples.",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Fill in the blanks with correct words.",
      option: [
        "(a) Long ago, people communicated using ............... and ............... on rocks.",
        "(b) Later, people started sending letters carried by ............... and ...............",
        "(c) Much later, the ............... service came into being. It was used to send ............... and important documents to others.",
        "(d) With time new ............... like the telephone, radio and ............... made it easier to communicate and share information.",
        "(e) Today, we have mobile phones and ............... that use ............... The internet helps us connect with anyone and anywhere in seconds.",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Tick (&#10003;) the correct option.",
      option: [
        "In the past, the most common method of communication was </br> (i) video calls </br> (ii) social media messages </br> (iii) letters </br> (iv) pigeons",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Today, Navya says we can send money online within seconds using",
      option: ["mobile phones", "postal orders", "parcels", "courier"],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "On a map, which direction is shown at the top?",
      option: ["East", "West", "South", "North"],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title: "Many people were coming to the hospital because",
      option: [
        "they needed surgery",
        "a free eye check-up camp was organised",
        "it was a holiday",
        "they wanted to visit friends",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title:
        "In her layout sketch, the places east of Navya's house are shown on which side of paper?",
      option: ["bottom side", "left side", "right side", "top side"],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Multiple choice questions",
    answer: ["Ans"],
    difficulty: "E",
    outcome: "Understand",
    mark: 1,
    question: {
      title:
        "Assertion (A) : On a map, North is shown upwards, South downwards, East on the right, and West on the left.",
      option: [
        "Both A and R are true, and R explains A.",
        "Both A and R are true, but R does not explain A.",
        "A is true, R is false.",
        "A is false, R is true.",
      ],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "In the blank boxes above, write the names of important places located in each direction from your house.",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["North"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "N stands for ",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["East"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "E stands for ",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["West"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "W stands for ",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Fill in the blanks",
    answer: ["South"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "S stands for ",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Ans"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "Write the full form of NEWS.",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Long answer type questions",
    answer: ["Ans"],
    difficulty: "H",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "Ask your elders how people give directions to someone’s house in modern times. Write their replies in your own words.",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Bus Stop"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "Unscramble each set of letters to form the correct word, using the hints provided. (a) TOPSUBS",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Post Office"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(b) TSCFPOIEFO",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Internet"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(c) EITNRENT",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Drum"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(d) DMUBREAST",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Barter"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "(a) What system did people use to exchange goods and services without coins?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Farmer and shepherd or potter and eggs"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(b) Which two specific trades are described in the story?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Finding right trade partner"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title:
        "(c) What challenges did traders face when using the barter system?",
      option: [""],
      image: "",
    },
  },
  {
    subject: "",
    class: "class-3",
    book: "class-3",
    chapter: "2. Exploring Our Neighbourhood",
    type: "Short answer type questions",
    answer: ["Money"],
    difficulty: "M",
    outcome: "Apply",
    mark: 1,
    question: {
      title: "(d) What invention made it easier to buy and sell quickly?",
      option: [""],
      image: "",
    },
  },
];
